create table if not exists public.unsubscribe_requests (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  email_normalized text not null,
  address_id bigint not null,
  address_name text,
  status text not null default 'pending' check (status in ('pending','processing','confirmed','expired','email_failed')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  confirmed_at timestamptz
);

create index if not exists unsubscribe_requests_email_idx on public.unsubscribe_requests (email_normalized);
create index if not exists unsubscribe_requests_expires_idx on public.unsubscribe_requests (expires_at);

alter table public.unsubscribe_requests enable row level security;

revoke all on table public.unsubscribe_requests from anon, authenticated;
grant all on table public.unsubscribe_requests to service_role;